# Project information
site_name: Wanna Res Like You
site_url: https://madvid.github.io/WannaResLikeYou
site_author: Matthieu David

# Repository
repo_name: madvid/WannaResLikeYou
repo_url: https://github.com/madvid/WannaResLikeYou

nav:
  - Home: index.md
  - About: about.md
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
